'use strict';
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

// Every artifact one revision generates. Stale revisions are pruned on build so
// the bundle directory — and the repository that ships it — keeps one copy.
const GENERATED = /^(?:runtime-[a-f0-9]{16}\.mjs|(?:core|embeddings)-runtime-[a-f0-9]{16}\.cjs)$/;

/** Plan one revision without touching disk: content hash, Host source, helper names. */
function revisionOf(root = __dirname) {
  // Cache identity must include the generator and every implementation dependency.
  const files = ['build.cjs', 'host.mjs', 'core.js', 'embeddings.js', 'client.js'];
  const sources = new Map(files.map(file => [file, fs.readFileSync(path.join(root, file), 'utf8')]));
  const hash = crypto.createHash('sha256');
  for (const [file, source] of sources) hash.update(JSON.stringify([file, source]));
  const revision = hash.digest('hex').slice(0, 16);
  const entry = `runtime-${revision}.mjs`;
  let host = sources.get('host.mjs');
  const helpers = [];
  // A query string on the ESM Host does NOT invalidate CommonJS dependencies.
  // Give each dependency a new physical path so both ESM and CJS caches change.
  for (const module of ['core', 'embeddings']) {
    const from = `import ${module} from './${module}.js';`;
    if (host.split(from).length !== 2) throw Error(`Expected exactly one ${module} import`);
    const helper = `${module}-runtime-${revision}.cjs`;
    host = host.replace(from, `import ${module} from './${helper}';`);
    helpers.push(helper);
  }
  return { revision, entry, helpers, host, sources };
}

function build(root = __dirname) {
  const { revision, entry, helpers, host, sources } = revisionOf(root);
  for (let index = 0; index < helpers.length; index++) {
    const module = ['core', 'embeddings'][index];
    fs.writeFileSync(path.join(root, helpers[index]), sources.get(`${module}.js`));
  }
  fs.writeFileSync(path.join(root, entry), `// Generated by build.cjs. Edit host.mjs and helpers, not this artifact.\n${host}`);
  fs.writeFileSync(path.join(root, 'cordis.patch.yml'), `- insert:\n    - id: workspace-memory\n      name: ./${entry}\n`);
  const keep = new Set([entry, ...helpers]);
  for (const file of fs.readdirSync(root)) {
    if (GENERATED.test(file) && !keep.has(file)) fs.rmSync(path.join(root, file));
  }
  return { revision, entry, helpers };
}

module.exports = { build, revisionOf };
if (require.main === module) console.log('Built workspace-memory runtime ' + build().revision);
